# classification problem

In [2]:
import numpy as np
import pandas as pd

In [3]:
np.random.seed(42)

n = 1000

data = pd.DataFrame({
    'offer': np.random.choice([0,1], size=n, p=[0.7,0.3]),
    'win': np.random.choice([0,1], size=n, p=[0.8,0.2]),
    'urgent': np.random.choice([0,1], size=n, p=[0.75,0.25])
})

data

     offer  win  urgent
0        0    0       0
1        1    0       0
2        1    1       1
3        0    0       0
4        0    1       0
..     ...  ...     ...
995      0    0       1
996      1    1       0
997      0    0       0
998      1    0       0
999      0    0       1

[1000 rows x 3 columns]

In [4]:
data['spam'] = (
    (data['offer'] == 1) &  ((data['win'] == 1) | (data['urgent'] == 1))
).astype(int)

data.head()

   offer  win  urgent  spam
0      0    0       0     0
1      1    0       0     0
2      1    1       1     1
3      0    0       0     0
4      0    1       0     0

# calculate the prior margine probabilty

In [5]:
# p (spam)
P_spam = data['spam'].mean() 
P_not_spam = 1 - P_spam

print("P(Spam):", P_spam)
print("P(Not Spam):", P_not_spam)

P(Spam): 0.108
P(Not Spam): 0.892

# calculate conditional probabilty
# p(offer = 1 | spam)

In [7]:
P_offer_given_spam = len(data[(data.offer==1) & (data.spam==1)]) / len(data[data.spam==1])
P_offer_given_notspam = len(data[(data.offer==1) & (data.spam==0)]) / len(data[data.spam==0])

print(P_offer_given_spam)
print(P_offer_given_notspam)

1.0
0.20179372197309417

# p(win=1| spam)

In [8]:
P_win_given_spam=len(data[(data.win==1) & (data.spam==1)]) /len(data[data.spam==1])
P_win_given_notspam = len(data[(data.win==1) & (data.spam==0)]) / len(data[data.spam==0])

print(P_win_given_spam)
print(P_win_given_notspam)

0.48148148148148145
0.17040358744394618

# p(urgent =1 |spam)

In [9]:
P_urgent_given_spam = len(data[(data.urgent==1) & (data.spam==1)]) / len(data[data.spam==1])
P_urgent_given_notspam = len(data[(data.urgent==1) & (data.spam==0)]) / len(data[data.spam==0])

print(P_urgent_given_spam)
print(P_urgent_given_notspam)

0.6851851851851852
0.2085201793721973

In [10]:
data['spam'] = (
    (data['offer'] == 0) &  ((data['win'] == 1) | (data['urgent'] == 1))
).astype(int)

data.head()

   offer  win  urgent  spam
0      0    0       0     0
1      1    0       0     0
2      1    1       1     0
3      0    0       0     0
4      0    1       0     1

# prior margineal probabillity

In [11]:
P_spam = data['spam'].mean() 
P_not_spam = 1 - P_spam

print("P(Spam):", P_spam)
print("P(Not Spam):", P_not_spam)

P(Spam): 0.298
P(Not Spam): 0.702

# calculate the conditional probability
# offers =0| spam

In [12]:
P_offer_given_spam = len(data[(data.offer==0) & (data.spam==1)]) / len(data[data.spam==1])
P_offer_given_notspam = len(data[(data.offer==0) & (data.spam==0)]) / len(data[data.spam==0])

print(P_offer_given_spam)
print(P_offer_given_notspam)

1.0
0.5897435897435898

# win=1 | spam

In [13]:
P_win_given_spam = len(data[(data.win==1) & (data.spam==1)]) / len(data[data.spam==1])
P_win_given_notspam = len(data[(data.win==1) & (data.spam==0)]) / len(data[data.spam==0])

print(P_win_given_spam)
print(P_win_given_notspam)

0.5100671140939598
0.07407407407407407

# urgent =1|spam

In [14]:
P_urgent_given_spam = len(data[(data.urgent==1) & (data.spam==1)]) / len(data[data.spam==1])
P_urgent_given_notspam = len(data[(data.urgent==1) & (data.spam==0)]) / len(data[data.spam==0])

print(P_urgent_given_spam)
print(P_urgent_given_notspam)

0.6241610738255033
0.10541310541310542

In [19]:
# Get needed probabilities

P_offer0_given_spam = 1 - (len(data[(data.offer==0) & (data.spam==1)]) / len(data[data.spam==1]))
# P_win0_given_spam = 1-0.48148148148148145

P_offer0_given_notspam = 1 - (len(data[(data.offer==0) & (data.spam==0)]) / len(data[data.spam==0]))

P_urgent_given_spam = len(data[(data.urgent==1) & (data.spam==1)]) / len(data[data.spam==1])

# Compute numerator for spam
numerator_spam = (
    P_spam *
    P_offer0_given_spam *
    P_win_given_spam *
    P_urgent_given_spam
)

print("Unnormalized Spam Probability:", numerator_spam)

Unnormalized Spam Probability: 0.0

In [21]:
# Get needed probabilities

P_offer0_given_notspam = 1 - (len(data[(data.offer==0) & (data.spam==0)]) / len(data[data.spam==0]))
P_urgent_given_spam = len(data[(data.urgent==1) & (data.spam==1)]) / len(data[data.spam==1])

numerator_notspam = (
    P_not_spam *
    P_offer0_given_notspam *
    P_win_given_notspam *
    P_urgent_given_notspam
)
numerator_notspam

np.float64(0.0022488129154795817)

In [22]:
print("Unnormalized Spam:", numerator_spam)
print("Unnormalized Not Spam:", numerator_notspam)

Unnormalized Spam: 0.0
Unnormalized Not Spam: 0.0022488129154795817

In [23]:
if numerator_spam > numerator_notspam:
    print("Manual Prediction: SPAM")
else:
    print("Manual Prediction: NOT SPAM")

Manual Prediction: NOT SPAM

In [24]:
# Define spam logic
data['spam'] = (
    (data['offer'] == 1) &  ((data['win'] == 1) | (data['urgent'] == 0))
).astype(int)

data.head()

   offer  win  urgent  spam
0      0    0       0     0
1      1    0       0     1
2      1    1       1     1
3      0    0       0     0
4      0    1       0     0

In [25]:
P_spam = data['spam'].mean() 
P_not_spam = 1 - P_spam

print("P(Spam):", P_spam)
print("P(Not Spam):", P_not_spam)

P(Spam): 0.232
P(Not Spam): 0.768

# calculate conditional probability
# offer =1|spam

In [26]:
P_offer_given_spam = len(data[(data.offer==1) & (data.spam==1)]) / len(data[data.spam==1])
P_offer_given_notspam = len(data[(data.offer==1) & (data.spam==0)]) / len(data[data.spam==0])

print(P_offer_given_spam)
print(P_offer_given_notspam)

1.0
0.07291666666666667

# win=1|spam

In [27]:
P_win_given_spam = len(data[(data.win==1) & (data.spam==1)]) / len(data[data.spam==1])
P_win_given_notspam = len(data[(data.win==1) & (data.spam==0)]) / len(data[data.spam==0])

print(P_win_given_spam)
print(P_win_given_notspam)

0.22413793103448276
0.19791666666666666

# urgent=0|spam

In [29]:
P_urgent_given_spam = len(data[(data.urgent==0) & (data.spam==1)]) / len(data[data.spam==1])
P_urgent_given_notspam = len(data[(data.urgent==0) & (data.spam==0)]) / len(data[data.spam==0])

print(P_urgent_given_spam)
print(P_urgent_given_notspam)

0.9224137931034483
0.6848958333333334

In [34]:


P_urgent0_given_spam = 1 - (len(data[(data.urgent==0) & (data.spam==1)]) / len(data[data.spam==1]))


P_urgent0_given_notspam = 1 - (len(data[(data.urgent==0) & (data.spam==0)]) / len(data[data.spam==0]))

P_urgent_given_spam = len(data[(data.urgent==0) & (data.spam==1)]) / len(data[data.spam==1])

# Compute numerator for spam
numerator_spam = (
    P_spam *
    P_offer_given_spam *
    P_urgent0_given_spam *
    P_urgent_given_spam
)

print("Unnormalized Spam Probability:", numerator_spam)

Unnormalized Spam Probability: 0.01660344827586207

In [35]:
# Get needed probabilities

P_urgent0_given_notspam = 1 - (len(data[(data.urgent==0) & (data.spam==0)]) / len(data[data.spam==0]))
P_urgent_given_spam = len(data[(data.urgent==0) & (data.spam==1)]) / len(data[data.spam==1])

numerator_notspam = (
    P_not_spam *
    P_offer_given_notspam *
    P_urgent0_given_notspam *
    P_urgent_given_notspam
)
numerator_notspam

np.float64(0.012085557725694444)

In [36]:
print("Unnormalized Spam:", numerator_spam)
print("Unnormalized Not Spam:", numerator_notspam)

Unnormalized Spam: 0.01660344827586207
Unnormalized Not Spam: 0.012085557725694444

In [37]:
if numerator_spam > numerator_notspam:
    print("Manual Prediction: SPAM")
else:
    print("Manual Prediction: NOT SPAM")

Manual Prediction: SPAM